### ISSUE TITLE
rustpotter-cli with dsnoop

### ISSUE THREAD

**Issue by Nortonko** [GiviMAD/rustpotter-cli#6]
Hi,
I need my microphone (capture device) to share with another app at the same time. I have therefore set up the dsnoop module in asound.conf. In the other application everything goes fine for me. But i get the following error when i run the rustpotter-cli command:
```
rustpotter-cli spot hey_pocitac.rpw
Spotting using models: ["hey_pocitac.rpw"]!
Input device: default
Input device config: SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Range { min: 185, max: 398915783 }, sample_format: F32 }
Begin recording...
thread 'main' panicked at 'Command failed: "A backend-specific error has occurred: ALSA function 'snd_pcm_hw_params_set_buffer_size' failed with error 'EINVAL: Invalid argument'"', src/cli/mod.rs:46:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
With direct microphone setup without dsnoop the rustpotter-cli command goes fine.
Is this an error related to the alsa setup or is the problem in rustpotter-cli?
Thanks

**Comment by GiviMAD** [comment]
Hey @Nortonko,
Never tried that, it was in my TODO list. Maybe using dsnoop doesn't allow to set a custom buffer size.

Anyway, with the changes introduced in the last version that is not a requirement anymore, so I can make setting a custom buffer size something optional. 

I'll look at it.

Probably I should also change the default "Input device config" selection, or add and option about it, because using a configuration with sample rate 16000, format F32 and 1 channel will cause no resampling to be done by rustpotter, so I think it will be better to use a config like that if available.

**Comment by GiviMAD** [comment]
Can you check if it's working with the latest release?

**Comment by Nortonko** [comment]
Hey @GiviMAD 
it's working now with latest release.
Thanks for your help and support.
